Brings the module up to current 1.0 standards
Closes #12 by adding the delete-job command to allowing thorough testing of the job life-cycle. Fixes #11 by implementing startup code that monitors the log file to ensure Jenkins is properly up. Closes #10 by updating tests, command headers and options handling to bring the module in-line with the latest conventions. Closes #8 by introducing the jenkins-home option and updating commands to use it.

diff --git a/commands/configure-rundeck-plugin/script b/commands/configure-rundeck-plugin/script
--- a/commands/configure-rundeck-plugin/script
+++ b/commands/configure-rundeck-plugin/script
@@ -1,29 +1,37 @@
 #!/usr/bin/env bash
 #
-#/ command: jenkins:configure-rundeck-plugin: ""Configure the Jenkins Rundeck plugin""
+#/ command: jenkins:configure-rundeck-plugin: "Configure the Jenkins Rundeck plugin"
 #
-#/ usage: rerun jenkins:configure-rundeck-plugin [ --password|-p <admin>] [ --restart|-r <false>] [ --url|-u <http://localhost:4440>] [ --username|-u <admin>] 
+#/ usage: rerun jenkins:configure-rundeck-plugin [options]
 #
-#/ variables: PASSWORD RESTART URL USERNAME
+#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
+#/ option variables: 
 
 # Read module function library.
 . $RERUN_MODULE_DIR/lib/functions.sh || { 
-  echo >&2 "Failed loading function library" ; exit 1 ; 
+  echo >&2 "Failed loading function library." ; exit 1 ; 
 }
 
 # Parse the command options.
-[ -r $RERUN_MODULE_DIR/commands/configure-rundeck-plugin/options.sh ] && {
-  . $RERUN_MODULE_DIR/commands/configure-rundeck-plugin/options.sh || exit 2 ;
+[[ -r $RERUN_MODULE_DIR/commands/configure-rundeck-plugin/options.sh ]] && {
+    . $RERUN_MODULE_DIR/commands/configure-rundeck-plugin/options.sh || rerun_die "Failed loading options parser."
+    rerun_options_parse "$@"
 }
 
-# Exit immediately upon non-zero exit. See [set](http://ss64.com/bash/set.html)
-set -e
+
+# Error handling
+# ---------------
+# * Trap calls `rerun_die` with standard message.
+# * Exit upon command errors or accessing unset variables.
+#   * See [set](http://ss64.com/bash/set.html)
+trap 'rerun_die "*** command failed: jenkins:configure-rundeck-plugin. ***"' ERR
+set -o nounset -o pipefail
 
 # ------------------------------
 # Your implementation goes here.
 # ------------------------------
 
-sed -e "s+\${URL}+${URL}+" -e "s+\${USERNAME}+${USERNAME}+" -e "s+\${PASSWORD}+${PASSWORD}+" $RERUN_MODULE_DIR/templates/org.jenkinsci.plugins.rundeck.RundeckNotifier.xml | sudo -u jenkins /bin/sh -c "cat > /var/lib/jenkins/org.jenkinsci.plugins.rundeck.RundeckNotifier.xml"
+sed -e "s+\${RUNDECK_URL}+${RUNDECK_URL}+" -e "s+\${RUNDECK_USERNAME}+${RUNDECK_USERNAME}+" -e "s+\${RUNDECK_PASSWORD}+${RUNDECK_PASSWORD}+" $RERUN_MODULE_DIR/templates/org.jenkinsci.plugins.rundeck.RundeckNotifier.xml | sudo -u jenkins /bin/sh -c "cat > ${JENKINS_HOME}/org.jenkinsci.plugins.rundeck.RundeckNotifier.xml"
 
 if [[ "${RESTART}" = "true" ]]
 then
diff --git a/commands/install-plugin/script b/commands/install-plugin/script
--- a/commands/install-plugin/script
+++ b/commands/install-plugin/script
@@ -1,31 +1,43 @@
 #!/usr/bin/env bash
 #
-#/ command: jenkins:install-plugin: ""Install plugin from the web""
+#/ command: jenkins:install-plugin: "Install plugin from the web"
 #
-#/ usage: rerun jenkins:install-plugin  --name|-n <> [ --restart|-r <false>] [ --url|-u <http://updates.jenkins-ci.org>] [ --version|-v <latest>] 
+#/ usage: rerun jenkins:install-plugin [ --restart|-r <false>] [ --jenkins-home|-j </var/lib/jenkins>] [ --plugin-url|-p <http://updates.jenkins-ci.org>]  --plugin-name|-p <> [ --plugin-version|-p <latest>] [ --jenkins-url|-j <http://localhost:8080>] 
 #
-#/ variables: NAME RESTART URL VERSION
+#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
+#/ option variables: RESTART JENKINS_HOME PLUGIN_URL PLUGIN_NAME PLUGIN_VERSION JENKINS_URL
 
 # Read module function library.
 . $RERUN_MODULE_DIR/lib/functions.sh || { 
-  echo >&2 "Failed loading function library" ; exit 1 ; 
+  echo >&2 "Failed loading function library." ; exit 1 ; 
 }
+
+# Error handling
+# ---------------
+# * Trap calls `rerun_die` with standard message.
+# * Exit upon command errors or accessing unset variables.
+#   * See [set](http://ss64.com/bash/set.html)
+trap 'rerun_die "*** command failed: jenkins:install-plugin/. ***"' ERR
+set -o nounset -o pipefail
 
 # Parse the command options.
-[ -r $RERUN_MODULE_DIR/commands/install-plugin/options.sh ] && {
-  . $RERUN_MODULE_DIR/commands/install-plugin/options.sh || exit 2 ;
+[[ -r $RERUN_MODULE_DIR/commands/install-plugin/options.sh ]] && {
+    . $RERUN_MODULE_DIR/commands/install-plugin/options.sh || rerun_die "Failed loading options parser."
+    rerun_options_parse "$@"
 }
-
-# Exit immediately upon non-zero exit. See [set](http://ss64.com/bash/set.html)
-set -e
 
 # ------------------------------
 # Your implementation goes here.
 # ------------------------------
 
-cd /var/lib/jenkins/plugins
+if [[ -d "${JENKINS_HOME}/plugins" ]]
+then
+  cd ${JENKINS_HOME}/plugins
+else
+  exit 1
+fi
 
-sudo -u jenkins wget -O ${NAME}.hpi ${URL}/download/plugins/${NAME}/${VERSION}/${NAME}.hpi
+sudo -u jenkins wget -O ${PLUGIN_NAME}.hpi ${PLUGIN_URL}/download/plugins/${PLUGIN_NAME}/${PLUGIN_VERSION}/${PLUGIN_NAME}.hpi
 
 if [[ "${RESTART}" = "true" ]]
 then
diff --git a/commands/install/script b/commands/install/script
--- a/commands/install/script
+++ b/commands/install/script
@@ -1,25 +1,43 @@
 #!/usr/bin/env bash
 #
-#/ command: jenkins:install: "Install Jenkins on RedHat distributions using Yum"
+#/ command: jenkins:install: "Install Jenkins"
 #
 #/ usage: rerun jenkins:install [options]
 #
-#/ variables: 
+#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
+#/ option variables: 
 
 # Read module function library.
-source $RERUN_MODULE_DIR/lib/functions.sh || { echo "Failed loading function library" >&2 ; exit 1 ; }
-
-# Parse the command options.
-[ -r $RERUN_MODULE_DIR/commands/install/options.sh ] && {
-  source $RERUN_MODULE_DIR/commands/install/options.sh || exit 2 ;
+. $RERUN_MODULE_DIR/lib/functions.sh || { 
+  echo >&2 "Failed loading function library." ; exit 1 ; 
 }
 
-# Exit immediately upon non-zero exit. See [set](http://ss64.com/bash/set.html)
-set -e
+# Parse the command options.
+[[ -r $RERUN_MODULE_DIR/commands/install/options.sh ]] && {
+    . $RERUN_MODULE_DIR/commands/install/options.sh || rerun_die "Failed loading options parser."
+    rerun_options_parse "$@"
+}
 
-sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
-sudo rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
-sudo yum -y install jenkins
+
+# Error handling
+# ---------------
+# * Trap calls `rerun_die` with standard message.
+# * Exit upon command errors or accessing unset variables.
+#   * See [set](http://ss64.com/bash/set.html)
+trap 'rerun_die "*** command failed: jenkins:install. ***"' ERR
+set -o nounset -o pipefail
+
+
+# ------------------------------
+# Your implementation goes here.
+# ------------------------------
+
+if ! rpm --quiet -q jenkins
+then
+  sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
+  sudo rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
+  sudo yum -y install jenkins
+fi
 
 exit $?
 
diff --git a/commands/restart/script b/commands/restart/script
--- a/commands/restart/script
+++ b/commands/restart/script
@@ -4,26 +4,36 @@
 #
 #/ usage: rerun jenkins:restart [options]
 #
-#/ variables: 
+#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
+#/ option variables: 
 
 # Read module function library.
 . $RERUN_MODULE_DIR/lib/functions.sh || { 
-  echo >&2 "Failed loading function library" ; exit 1 ; 
+  echo >&2 "Failed loading function library." ; exit 1 ; 
 }
 
 # Parse the command options.
-[ -r $RERUN_MODULE_DIR/commands/restart/options.sh ] && {
-  . $RERUN_MODULE_DIR/commands/restart/options.sh || exit 2 ;
+[[ -r $RERUN_MODULE_DIR/commands/restart/options.sh ]] && {
+    . $RERUN_MODULE_DIR/commands/restart/options.sh || rerun_die "Failed loading options parser."
+    rerun_options_parse "$@"
 }
 
-# Exit immediately upon non-zero exit. See [set](http://ss64.com/bash/set.html)
-set -e
+
+# Error handling
+# ---------------
+# * Trap calls `rerun_die` with standard message.
+# * Exit upon command errors or accessing unset variables.
+#   * See [set](http://ss64.com/bash/set.html)
+trap 'rerun_die "*** command failed: jenkins:restart. ***"' ERR
+set -o nounset -o pipefail
+
 
 # ------------------------------
 # Your implementation goes here.
 # ------------------------------
 
-sudo service jenkins restart
+rerun jenkins:stop
+rerun jenkins:start
 
 exit $?
 
diff --git a/commands/start/script b/commands/start/script
--- a/commands/start/script
+++ b/commands/start/script
@@ -2,22 +2,68 @@
 #
 #/ command: jenkins:start: "Start Jenkins"
 #
-#/ usage: rerun jenkins:start [options]
+#/ usage: rerun jenkins:start [ --jenkins-log|-j </var/log/jenkins/jenkins.log>] [ --count|-c <60>] 
 #
-#/ variables: 
+#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
+#/ option variables: JENKINS_LOG COUNT
 
 # Read module function library.
-source $RERUN_MODULE_DIR/lib/functions.sh || { echo "Failed loading function library" >&2 ; exit 1 ; }
-
-# Parse the command options.
-[ -r $RERUN_MODULE_DIR/commands/start/options.sh ] && {
-  source $RERUN_MODULE_DIR/commands/start/options.sh || exit 2 ;
+. $RERUN_MODULE_DIR/lib/functions.sh || { 
+  echo >&2 "Failed loading function library." ; exit 1 ; 
 }
 
-# Exit immediately upon non-zero exit. See [set](http://ss64.com/bash/set.html)
-set -e
+# Parse the command options.
+[[ -r $RERUN_MODULE_DIR/commands/start/options.sh ]] && {
+    . $RERUN_MODULE_DIR/commands/start/options.sh || rerun_die "Failed loading options parser."
+    rerun_options_parse "$@"
+}
 
-sudo service jenkins start
+
+# Error handling
+# ---------------
+# * Trap calls `rerun_die` with standard message.
+# * Exit upon command errors or accessing unset variables.
+#   * See [set](http://ss64.com/bash/set.html)
+trap 'rerun_die "*** command failed: jenkins:start. ***"' ERR
+set -o nounset -o pipefail
+
+
+# ------------------------------
+# Your implementation goes here.
+# ------------------------------
+
+if ! rerun jenkins:status
+then
+  #
+  # Start Jenkins:
+  #
+  sudo /sbin/service jenkins start
+
+  #
+  # Wait for the log file to exist:
+  #
+  count=0
+  while [[ $count -lt $COUNT ]]
+  do
+    if sudo test -e $JENKINS_LOG
+    then
+      break
+    fi
+
+    sleep $INTERVAL
+    count=$((count+1))
+  done
+
+  if [[ $count -eq $COUNT ]]
+  then
+    exit 1
+  fi
+
+  #
+  # Wait for the startup message to appear or timeout:
+  #
+  timeout $((INTERVAL*COUNT)) grep -q '^INFO: Jenkins is fully up and running' <(sudo tail -n 0 -f $JENKINS_LOG)
+fi
 
 exit $?
 
