Close #25 by updating command headers, etc to be compatible with the latest Rerun build.

diff --git a/commands/add-maven/script b/commands/add-maven/script
--- a/commands/add-maven/script
+++ b/commands/add-maven/script
@@ -1,36 +1,67 @@
 #!/usr/bin/env bash
-#
-#/ command: jenkins:add-maven: "Adds a Maven installation to the Jenkins configuration"
-#
-#/ usage: rerun jenkins:add-maven [ --maven-name|-m <maven>] [ --maven-home|-m </usr/share/maven>] [ --jenkins-home </var/lib/jenkins>] [ --restart <false>] 
-#
-#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
-#/ option variables: MAVEN_NAME MAVEN_HOME JENKINS_HOME RESTART
 
-# Read module function library.
-. $RERUN_MODULE_DIR/lib/functions.sh || { 
+# To implement this command, edit the "Command implementation" section below. 
+
+# Usage
+# -----
+
+# Comments prefixed with `#/` are managed by stubbs.
+# The `command` and `usage` comments describe the command
+# and show its options.
+# 
+#/ command: jenkins:add-maven: "Adds a Maven installation to the Jenkins configuration"
+#/ usage: rerun jenkins:add-maven [ --maven-name <maven>] [ --maven-home|-m </usr/share/maven>] [ --jenkins-home </var/lib/jenkins>] [ --restart|-r <false>] 
+
+# Load common functions
+# ---------------------
+
+# Load the function library for this module.
+# This loads rerun functions, too.
+. $RERUN_MODULE_DIR/lib/functions.sh add-maven || { 
   echo >&2 "Failed loading function library." ; exit 1 ; 
 }
 
-# Parse the command options.
-[[ -r $RERUN_MODULE_DIR/commands/add-maven/options.sh ]] && {
-    . $RERUN_MODULE_DIR/commands/add-maven/options.sh || rerun_die "Failed loading options parser."
-    rerun_options_parse "$@"
-}
-
-
 # Error handling
 # ---------------
-# * Trap calls `rerun_die` with standard message.
-# * Exit upon command errors or accessing unset variables.
-#   * See [set](http://ss64.com/bash/set.html)
-trap 'rerun_die "*** command failed: jenkins:add-maven. ***"' ERR
+
+# This script is designed to _fail-fast_.
+
+# Trap errors and exit. The call to `rerun_die` will print the
+# the error message and exit with the error command exit status. 
+
+trap 'rerun_die $? "*** command failed: jenkins:add-maven. ***"' ERR
+
+# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
+# so a pipeline return status is the value of the last 
+# (rightmost) command to exit with non-zero status.
+#
+# [set]: http://ss64.com/bash/set.html
+# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html
+
 set -o nounset -o pipefail
 
+# Command variables
+# -----------------
 
-# ------------------------------
-# Your implementation goes here.
-# ------------------------------
+# This command script can access the following variables
+# declared by `rerun` or by the option parser function.
+
+#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
+#/ option-variables: MAVEN_NAME MAVEN_HOME JENKINS_HOME RESTART
+
+# The `rerun_options_parse` function processes the command line
+# arguments. Each accepted command line flag results in setting 
+# one the corresponding option variables.
+
+rerun_options_parse "$@"
+
+
+# Command implementation
+# ----------------------
+
+# - - -
+# Put the command implementation here.
+# - - -
 
 sed -e "s+\${MAVEN_NAME}+${MAVEN_NAME}+" -e "s+\${MAVEN_HOME}+${MAVEN_HOME}+" $RERUN_MODULE_DIR/templates/hudson.tasks.Maven.xml | sudo -u jenkins /bin/sh -c "cat > ${JENKINS_HOME}/hudson.tasks.Maven.xml"
 
