Closes #22 by adding the standard deploy and remove commands.

diff --git a/commands/cleanup/script b/commands/cleanup/script
--- a/commands/cleanup/script
+++ b/commands/cleanup/script
@@ -1,44 +1,37 @@
 #!/usr/bin/env bash
 #
-#/ command: jenkins:stop: "Stop Jenkins"
+#/ command: jenkins:cleanup: "Remove Jenkins working files from the system."
 #
-#/ usage: rerun jenkins:stop [options]
+#/ usage: rerun jenkins:cleanup [ --jenkins-home </var/lib/jenkins>] 
 #
 #/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
-#/ option variables: 
+#/ option variables: JENKINS_HOME
 
 # Read module function library.
 . $RERUN_MODULE_DIR/lib/functions.sh || { 
   echo >&2 "Failed loading function library." ; exit 1 ; 
 }
 
-# Parse the command options.
-[[ -r $RERUN_MODULE_DIR/commands/stop/options.sh ]] && {
-    . $RERUN_MODULE_DIR/commands/stop/options.sh || rerun_die "Failed loading options parser."
-    rerun_options_parse "$@"
-}
-
-
 # Error handling
 # ---------------
 # * Trap calls `rerun_die` with standard message.
 # * Exit upon command errors or accessing unset variables.
 #   * See [set](http://ss64.com/bash/set.html)
-trap 'rerun_die "*** command failed: jenkins:stop. ***"' ERR
+trap 'rerun_die "*** command failed: jenkins:cleanup. ***"' ERR
 set -o nounset -o pipefail
+
+# Parse the command options.
+[[ -r $RERUN_MODULE_DIR/commands/cleanup/options.sh ]] && {
+    . $RERUN_MODULE_DIR/commands/cleanup/options.sh || rerun_die "Failed loading options parser."
+    rerun_options_parse "$@"
+}
 
 
 # ------------------------------
 # Your implementation goes here.
 # ------------------------------
 
-if /sbin/chkconfig jenkins
-then
-  if rerun jenkins:status
-  then
-    sudo /sbin/service jenkins stop
-  fi
-fi
+sudo rm -rf ${JENKINS_HOME} /var/cache/jenkins /var/log/jenkins /etc/yum.repos.d/jenkins.repo.rpmsave
 
 exit $?
 
diff --git a/commands/status/script b/commands/status/script
--- a/commands/status/script
+++ b/commands/status/script
@@ -32,7 +32,11 @@ set -o nounset -o pipefail
 # Your implementation goes here.
 # ------------------------------
 
-sudo /sbin/service jenkins status
+# Capture the init script's exit code without displaying superflous output.
+if ! rc=$(sudo /sbin/service jenkins status >/dev/null)$?
+then
+  exit $rc
+fi
 
 exit $?
 
